### ISSUE TITLE
不能运行测试程序，import torch出错

### ISSUE THREAD

**Issue by storyxlx** [sophgo/torch-tpu#2]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/root/sophon/test_torch.py", line 1, in <module>
    import torch
  File "/root/anaconda3/envs/sophon/lib/python3.10/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/root/anaconda3/envs/sophon/lib/python3.10/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/root/anaconda3/envs/sophon/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/root/anaconda3/envs/sophon/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/root/anaconda3/envs/sophon/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/root/anaconda3/envs/sophon/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
tensor([[[-0.0423,  0.1661, -0.2942],
         [ 0.0332, -0.1093, -0.0782],
         [-0.1093,  0.0768, -0.4314],
         ...,
         [ 0.3929,  0.0626, -0.2317],
         [-0.2231,  0.2673, -0.2224],
         [ 0.1604,  0.0774, -0.3724]],

        [[-0.2736,  0.0202, -0.0795],
         [-0.1033,  0.0064,  0.1336],
         [-0.1728,  0.2518, -0.3077],
         ...,
         [-0.2807,  0.0492, -0.4240],
         [-0.1184, -0.2715,  0.0113],
         [ 0.1578,  0.3606, -0.4136]],

        [[ 0.0672,  0.1239, -0.2936],
         [ 0.1396, -0.0153, -0.1790],

**Comment by Qs315490** [comment]
>A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
>
>If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

这个问题是numpy版本高了，目前pytorch带的扩展是numpy1.x的。降级numpy就行
```bash
conda install "numpy<2"
# 或者
pip install -U "numpy<2"
```
